apiVersion: v1
kind: ConfigMap
metadata:
  name: hwameistor-scheduler-config
  namespace: hwameistor
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: hwameistor-scheduler
    leaderElection:
      leaderElect: true
      lockObjectName: hwameistor-scheduler
      resourceLock: leases
    plugins:
      filter:
        enabled:
          - name: hwameistor-scheduler-plugin
      reserve:
        enabled:
          - name: hwameistor-scheduler-plugin
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwameistor-scheduler
  namespace: hwameistor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwameistor-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hwameistor-scheduler
    spec:
      serviceAccount: hwameistor-admin
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      containers:
      - args:
        - -v=2
        - --bind-address=0.0.0.0
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=false
        - --leader-elect-resource-name=hwameistor-scheduler
        - --config=/etc/hwameistor/scheduler-config.yaml
        - --leader-elect-resource-namespace=hwameistor
        image: ghcr.io/hwameistor/scheduler:latest
        imagePullPolicy: IfNotPresent
        name: scheduler
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/hwameistor/
          name: hwameistor-scheduler-config
          readOnly: true
      volumes:
      - hostPath:
          path: /etc/kubernetes/admin.conf
          type: FileOrCreate
        name: kubeconfig
      - configMap:
          name: hwameistor-scheduler-config
          items:
          - key: scheduler-config.yaml
            path: scheduler-config.yaml
        name: hwameistor-scheduler-config
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Exists