apiVersion: v1
kind: ConfigMap
metadata:
  name: hwameistor-scheduler-config
  namespace: hwameistor-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: hwameistor-scheduler
        plugins:
          filter:
            enabled:
            - name: hwameistor-scheduler-plugin
    leaderElection:
      leaderElect: true
      resourceName: hwameistor-scheduler
    clientConnection:
      kubeconfig: /etc/kubernetes/scheduler.conf

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwameistor-scheduler
  namespace: hwameistor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwameistor-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hwameistor-scheduler
    spec:
      serviceAccount: storage-admin
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      containers:
      - args:
        - -v=2
        - --bind-address=0.0.0.0
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=false
        - --leader-elect-resource-name=hwameistor-scheduler
        - --config=/etc/hwameistor/scheduler-config.yaml
        - --leader-elect-resource-namespace=hwameistor-system  
        image: ghcr.io/hwameistor/scheduler:v0.1.2
        imagePullPolicy: IfNotPresent
        name: scheduler
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/hwameistor/
          name: hwameistor-scheduler-config
          readOnly: true
      volumes:
      - hostPath:
          path: /etc/kubernetes/admin.conf
          type: FileOrCreate
        name: kubeconfig
      - configMap:
          name: hwameistor-scheduler-config
          items:
          - key: scheduler-config.yaml
            path: scheduler-config.yaml
        name: hwameistor-scheduler-config
